coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
comment:
  layout: "files, diff, flags, components"
  behavior: default
