# ---------- General ----------
line-length = 140         # bump to 140 to defuse most E501 hits
target-version = "py310"

# ---------- Rules ----------
[lint]
select = ["E", "F", "I", "B", "UP"]     # style, bugs, import-order, pyupgrade
ignore = ["E203", "E266"]               # common formatter compat

[lint.per-file-ignores]
"tests/**/*" = ["B011", "E501"]         # allow long lines & assert False in tests

# ---------- Import sorting (via Ruff) ----------
[lint.isort]
known-first-party = [
  "agents", "inputs", "orchestrators", "reports", "schemas", "tools"
]
combine-as-imports = true
