# ---------- General ----------
line-length = 100
target-version = "py310"

# ---------- Lint rules ----------
[lint]
# E: pycodestyle, F: pyflakes, I: isort, B: flake8-bugbear, UP: pyupgrade
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203", "E266"]  # common ignores; tweak as you like

# Per-file allowances (tests are often special)
[lint.per-file-ignores]
"tests/**/*" = ["B011"]

# ---------- isort (via Ruff) ----------
[lint.isort]
known-first-party = ["ai_real_estate_deal_analyzer"]  # <- update if your package name differs
known-third-party = ["pydantic", "pytest", "numpy", "pandas"]
combine-as-imports = true
